### PR TITLE
Management tags

### PR DESCRIPTION
**Pull request by mdo997**

### CODE REVIEW

**Comment by carolynrehm** [comment]
Which is the appropriate back end branch that corresponds with this? "content-tags"?

**Comment by mdo997** [comment]
Yes Ma'am,
It will be content-tags for the back end

**Comment by mdo997** [comment]
@carolynrehm Fixed the merging conflicts, please review. Thank you!

**Comment by mdo997** [comment]
@carolynrehm, content-tags frontend, I have implemented user-confirmation when deleting a tag. Thank you!

**Comment by mdo997** [comment]
@carolynrehm deleted the .editor for merging

**Pull request merged**
