### PR TITLE
Feature refactor radio chris coleman

### PR DESCRIPTION
**Pull request by chrstphrclmn**
Updated Search functionality for both Content and Requests to allow for multiple format selection (i.e. checkbox) vs previous radio button implementation. (Note, requires content-service pull request that I am about to create for backend functionality).

Also changed radio button selection on Content and Request creation to more uniform button tab selection.  No backend changes required as functionality remained the same.

### CODE REVIEW

**Review by carolynrehm — CHANGES_REQUESTED** [review]
Build checks failed

**Comment by carolynrehm** [comment]
This also has a lot of curriculum related code. Include only the changes required for the radio button refactor

**Comment by chrstphrclmn** [comment]
> This also has a lot of curriculum related code. Include only the changes required for the radio button refactor

So I had to pull from Michael's feature branch in order to deal with some CSS issues from him implementing Material and along with that came his curriculum changes.  I realize that's not ideal, but once his pull is accepted they shouldn't be considered changes anymore.  

That being said, I can try and manually delete all of that implementation but I fear I would end up breaking something in the process.

**Review by carolynrehm — CHANGES_REQUESTED** [review]
Pull from dev and resolve merge conflicts

**Comment by chrstphrclmn** [comment]
Changed to other branch, see format refactor

**Pull request closed without merging**
